
DELETE SCRIPT e_audit_DEL_GetACLandTableInfo OK


DELETE v_GetUserSetExactOnOff OK
DELETE v_GetVersionMajor OK
DELETE v_GetVersionMinor OK
DELETE v_GetVersionPatch OK
DELETE v_GetVersionType OK
DELETE v_GetVersionBuild OK

DELETE v_GetOpenProjectPath OK
DELETE v_GetFieldContentOfFirstRecord OK
DELETE v_GetOpenViewFieldName OK
DELETE v_GetOpenViewFieldWidth OK
DELETE v_GetOpenViewFieldNumber OK
DELETE v_GetOpenViewName  OK
DELETE v_GetTableViewNameNumber OK
DELETE v_GetTableViewName OK
DELETE v_GetProjectTableFileNameNum OK
DELETE v_GetOpenProjectName OK
DELETE v_GetNumberOfTables OK
DELETE v_GetProjectTableName OK
DELETE v_GetProjectTableFileName OK
DELETE v_GetRelationIndex OK
DELETE v_GetRelationField OK
DELETE v_GetRelationTableName OK
DELETE v_GetNumberOfRelations OK
DELETE v_GetLogicalFields OK
DELETE v_GetDateFields OK
DELETE v_GetNumericFields OK
DELETE v_GetCharFields OK
DELETE v_GetNumberOfFields OK
DELETE v_GetNumberOfLogical OK
DELETE v_GetNumberOfDate OK
DELETE v_GetNumberOfNumeric OK
DELETE v_GetNumberOfChar OK
DELETE v_GetFieldnamesDecimals OK
DELETE v_GetFieldnamesDescription OK
DELETE v_GetFieldnamesExpression OK
DELETE v_GetFieldnamesLength OK
DELETE v_GetFieldnamesStartPos OK
DELETE v_GetFieldnamesType OK
DELETE v_GetFieldnames OK
DELETE v_GetRecordLength OK
DELETE v_GetDisplayTime OK
DELETE v_GetDisplayDate OK
DELETE v_GetOpenFileName OK
DELETE v_GetOpenTableName OK
DELETE v_GetDateFormat OK
DELETE v_GetDecimalSymbol OK
DELETE v_GetViewFilter OK
DELETE v_GetOpenLogFileName OK
DELETE v_valid_characters OK
DELETE v_default_language OK


SET ECHO ON
SET SAFETY ON
